openapi: 3.0.0
info:
  title: TV API
  version: 0.0.0
tags: []
paths:
  /api/v1/videos:
    get:
      operationId: Videos_list
      description: ビデオ一覧取得
      parameters:
        - name: page
          in: query
          required: false
          description: ページ番号
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
          explode: false
        - name: size
          in: query
          required: false
          description: 1ページあたりの最大取得件数
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 30
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoPage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: Videos_create
      description: ビデオ作成
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoCreate'
  /api/v1/videos/{id}:
    get:
      operationId: Videos_get
      description: ビデオ詳細取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      operationId: Videos_update
      description: ビデオ更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoUpdate'
    delete:
      operationId: Videos_delete
      description: ビデオ削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/videos/{id}/file:
    get:
      operationId: Videos_file
      description: ビデオファイル配信
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            video/webm:
              schema:
                type: string
                format: binary
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/videos/{id}/thumbnail:
    get:
      operationId: Videos_thumbnail
      description: サムネイル画像取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      description: エラーレスポンス
    Pager:
      type: object
      required:
        - page
        - size
        - totalCount
      properties:
        page:
          type: integer
          format: int32
          minimum: 1
          description: ページ番号
        size:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
          description: 1ページあたりの最大取得件数
        totalCount:
          type: integer
          format: int32
          minimum: 0
          description: ページに含まれているものも含まれていないものも合わせた対象の全数
      description: |-
        レスポンスのページネーション情報。
        ページに含まれる対象の数は以下で求められる。

        ```
        min(size, totalCount - size * (page - 1))
        ```
    RecordingStatus:
      type: object
      required:
        - recording
      properties:
        recording:
          type: boolean
          description: 録画中かどうか
        currentVideo:
          allOf:
            - $ref: '#/components/schemas/Video'
          description: 現在録画中のビデオ
      description: 録画ステータスレスポンス
    Video:
      type: object
      required:
        - id
        - title
        - filename
        - startedAt
        - audioActivityRatio
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          format: int64
          description: ビデオID
          readOnly: true
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: タイトル
        filename:
          type: string
          minLength: 1
          maxLength: 255
          description: ファイル名
        startedAt:
          type: string
          format: date-time
          description: 録画開始時刻(UTC)
        finishedAt:
          type: string
          format: date-time
          description: 録画終了時刻(UTC)
        audioActivityRatio:
          type: number
          format: double
          description: 音声アクティビティ率(%)
        createdAt:
          type: string
          format: date-time
          description: 作成日時
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: 更新日時
          readOnly: true
      description: 録画ビデオ
    VideoCreate:
      type: object
      required:
        - title
        - filename
        - startedAt
        - finishedAt
        - audioActivityRatio
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        filename:
          type: string
          minLength: 1
          maxLength: 255
        startedAt:
          type: string
          format: date-time
        finishedAt:
          type: string
          format: date-time
        audioActivityRatio:
          type: number
          format: double
          description: 音声アクティビティ率(%)
      description: ビデオ作成リクエスト
    VideoPage:
      type: object
      required:
        - pager
        - data
      properties:
        pager:
          $ref: '#/components/schemas/Pager'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Video'
      description: ビデオページレスポンス
    VideoUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        filename:
          type: string
          minLength: 1
          maxLength: 255
        startedAt:
          type: string
          format: date-time
        finishedAt:
          type: string
          format: date-time
        audioActivityRatio:
          type: number
          format: double
          description: 音声アクティビティ率(%)
      description: ビデオ更新リクエスト
servers:
  - url: http://localhost:8080
    description: Development server
    variables: {}
